project_id = "wksgvhktytkkgzarbwmc"

[functions.create-invitation]
verify_jwt = true

[functions.create-user-direct]
verify_jwt = true

[functions.validate-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false
